###################################
##  Uses IFTTT to notify me of bad logins.
###################################

- alias: Login Failure
  id: 814c48ea-e2e1-4b75-92b0-581081af5ce5
  
  trigger:
    platform: template
    value_template: "{{ states('persistent_notification.httplogin') != 'unknown' }}"

  action:
    - service: script.notify_engine
      data:
        value1: 'Bad Login: '
        value2: 'There was a Hack attempt!'
        value3: 'Go Check the GUI for details.'
        who: 'chris'
        apns_id: 'information'

        #################################################################
        ## Clear Erroneous Failed Login Notifications
        #################################################################

- alias: System - Clear Erroneous Failed Login Notifications
  id: c9eaff0d-53c0-4f5e-a41f-a9ea6f3d349d

  trigger:
    - platform: state
      entity_id: persistent_notification.http_login
      to: 'notifying'

  action:
    - delay: "00:00:01"
    - service: persistent_notification.dismiss
      data:
        notification_id: http-login
