        ##########################################################
        ## Reset Overrides at 7a
        ##########################################################

- alias: System - Reset Overrides at 5a
  id: 194a3711-a597-4e00-9d4d-f1d476980aa0

  trigger:
   - platform: time
     at: '05:00:00'

  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'

  action:
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.disable_climate
        - input_boolean.disable_notifications
        - input_boolean.disable_doorbell
        - input_boolean.disable_door_open_lights_on
        - input_boolean.disable_exterior_on_sunset
        - input_boolean.disable_exterior_off_night
        - input_boolean.disable_home_away
        - input_boolean.disable_interior_lights_sunset
        - input_boolean.disable_lock_unlock_doors
        - input_boolean.disable_media_lights
        - input_boolean.disable_motion
        - input_boolean.disable_occupancy
        - input_boolean.disable_rainy_day
        - input_boolean.disable_water_automations
        - input_boolean.disable_startup_notifications
        - input_boolean.disable_blinds
        - input_boolean.disable_roomba
        
        ##########################################################
        ## Disable Erroneous Startup Notifications
        ##########################################################

- alias: System - Disable Erroneous Startup Notifications
  id: d75e1f74-3c66-4b10-a319-711477164d4e

  trigger:
    - platform: homeassistant
      event: start

  action:
    - service: homeassistant.turn_on
      entity_id:
        - input_boolean.disable_startup_notifications
    - delay: 00:02:00
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.disable_startup_notifications
