######################################################################
##  Who's day is it anyway? Pretty sure my parent's didn't code to figure this out.
######################################################################
- alias: 'responsibilities'
  id: e1ae91e4-c44d-4dbc-a37c-4ddafdc66241
  mode: single
  trigger:

    - platform: state
      entity_id: input_boolean.responsibilities
      to: 'on'

  action:
    - service: script.speech_engine
      data:
        call_responsibilities: 1
