###################################
##  Sunrise stuff
###################################

- alias: 'Sunrise Turn Off'
  id: d0db568c-0aa2-42cc-b5be-ba546e39b640
  trigger:
    - platform: sun
      event: sunrise
      offset: '-02:00:00'

  action:
#    - service: homeassistant.turn_off
#      entity_id:
#        - group.landscaping
    - wait_template: >-
       {{ states.sun.sun.state == 'above_horizon' }}

    - service: homeassistant.turn_off
      entity_id:
        - group.exterior_lights

    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.guest_mode
    - service: homeassistant.update_entity  #Look for a new Home Assistant Version
      entity_id: binary_sensor.updater
