    
######################################################################
##  Stuff that needs to happen when we are out of bed
######################################################################

- alias: 'Time to wake up!'
  id: 16a3b9c5-1faa-410e-a7e1-249a9f861e07
  trigger:
    - platform: state
      entity_id: binary_sensor.master_bedroom_door
      to: 'on'

  condition:
    - condition: state
      entity_id: group.family
      state: home
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: time
      after: '07:00:00'
      before: '11:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id:
        - switch.amps
        - light.kitchen_lights
    - service: input_boolean.turn_on
      entity_id: input_boolean.good_morning
    