amp_settings:
  sequence:
    - service: media_player.volume_set
      data:
        entity_id: >-
            {% if media_player | length == 0 %}
              {% set media_player = [
                'media_player.office_speaker',
                'media_player.kitchen_speaker'
              ] %}
            {% endif %}
            {{ media_player }}
        volume_level: >-
          {% if volume_level is none %}
            {% if now().strftime('%H')|int < 12 and now().strftime('%H')|int > 6 %}
              0.5
            {% elif now().strftime('%H')|int > 12 and now().strftime('%H')|int < 20 %}
              0.7
            {% else %}
              0.5
            {% endif %}
          {% endif %}
          {{volume_level}}
    - condition: state
      entity_id: switch.amps
      state: 'off'
#    - condition: state
#      entity_id: group.bed
#      state: 'off'

    - service: switch.turn_on
      data:
        entity_id: switch.amps