#############################################################################################################
###  This part of the automation is hidden due to the External IP address being exposed  ##
- platform: template
  sensors:
    ipchange:
      friendly_name: "IP Change Detected"
      value_template: >
        {% if is_state('sensor.external_ip', '162.225.61.206') %}
          False
        {% elif is_state('sensor.external_ip', 'unknown') %}
          False
        {% else %}
          True
        {% endif %}

#############################################################################################################
