#-------------------------------------------
#  When the back door opens, at night, turn on deck string lights.
#-------------------------------------------

- alias: Deck light helper
  id: 9521d521-00dc-4116-b467-5150735fcff9
  trigger:
    - platform: state
      entity_id: binary_sensor.backdoor
      to: 'on'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: light.string_lights
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_exterior_off_night
      state: 'off'

  action:
    - service: homeassistant.turn_on
      entity_id: light.string_lights
    - wait_template: >-
        {{ states.lock.backdoor_lock.state == 'locked' }}
    - service: homeassistant.turn_off
      entity_id: light.string_lights
