#################################################################
## Door Automations
#################################################################

        ##########################################################
        ## Turn On Living Room Lights when Front Door Opens
        ##########################################################

- alias: Doors - Turn On Living Room Lights when Front Door Opens
  id: 5ec4a784-4472-4388-ae99-1b5e708985e6

  triggers:
    - trigger: state
      entity_id: binary_sensor.frontdoor
      from: 'off'
      to: 'on'

  conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_door_open_lights_on
      state: 'off'
    - condition: state
      entity_id: light.dining_room_can_lights
      state: 'off'

  actions:
    - action: light.turn_on
      target:
        entity_id:
          - light.dining_room_can_lights
          - light.kitchen_can_lights


#################################################################
## Notifications
#################################################################
