homeassistant:
  customize:

    sensor.holiday:

      icon: mdi:beach
      friendly_name: US Holiday
    sensor.flag:

      icon: mdi:flag
      friendly_name: Flag Day

###############################################################################
# Sensor updates once every 4 hours (14400 seconds) & runs 6 times in 24 hours
#
# First it checks for holiday in static section, if that doesn't exist,
# it checks in the dynamic section. If neither exists, the value will be empty
###############################################################################
sensor:
  - platform: rest
    resource: https://raw.githubusercontent.com/chrisalfons0/Home-AssistantConfig-all/master/json_data/holidays.json
    name: Holiday
    scan_interval: 14400
    value_template: >
      {% set today = now().month  ~ '/' ~ now().day  %}
      {% set holiday = value_json.MAJOR_US.static[today] if today in value_json.MAJOR_US.static else "" %}
      {% if holiday | trim == "" %}
        {% set today = now().month  ~ '/' ~ now().day ~ '/' ~ now().year %}
        {% set holiday = value_json.MAJOR_US.dynamic[today] if today in value_json.MAJOR_US.dynamic else "" %}
      {% endif %}
      {{ holiday }}

################################################################################
# Sensor Uses Flag data generated by AI
################################################################################
  - platform: rest
    resource: https://raw.githubusercontent.com/chrisalfons0/Home-AssistantConfig-all/master/json_data/flag_days.json
    name: Flag
    scan_interval: 14400
    value_template: >-
      {% set now_string = now().strftime('%m/%d') %}
      {% set now_full_string = now().strftime('%m/%d/%Y') %}
      {% if value_json is defined and value_json.Flag_Days_US is defined %}
        {% set static_days = value_json.Flag_Days_US.static %}
        {% set dynamic_days = value_json.Flag_Days_US.dynamic %}
        {% if static_days is defined and now_string in static_days %}
          True
        {% elif dynamic_days is defined %}
          {% for day_val in dynamic_days %}
            {% if day_val.date == now_full_string %}
              True
            {% endif %}
          {% endfor %}
        {% else %}
          False
        {% endif %}
      {% else %}
        
      {% endif %}

###############################################################################
# Automation that notifies of a Holiday "state" change
###############################################################################
automation:
  - alias: Notify Holiday State Change
    id: 77ce63e4-0a6e-485e-85a8-687a5a2d9df7

    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - sensor.holiday
    condition:
      - condition: template
        value_template: "{{ states('sensor.holiday') != 'unknown' }}"
      - condition: template
        value_template: "{{ states.sensor.holiday.state | trim != '' }}"
    action:
      - service: persistent_notification.create
        data:
          message: 'Today is {{ states.sensor.holiday.state }}.'
          title: '{{ states.sensor.holiday.state }}'

      - delay: '0{{ (range(4, 8)|random|int) }}:{{ range(0,5) | random | int }}{{ range(0,9) | random | int }}:{{ range(0,5) | random | int }}{{ range(0,9) | random | int }}'
